# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy PHP app to Azure Web App - educationapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for Azure login
      contents: read    # Required for actions/checkout

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2F9D66D4E81442B393F8E9D2EA8F58A4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A50BCB7A59AE4F19B68E2076A2687C69 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3574D5C87B943E5B4978AE90AE71C01 }}

      # Deploy directly from repo root
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'educationapp'
          slot-name: 'Production'
          package: .
